import 'package:cloud_firestore/cloud_firestore.dart';

class FirebaseServiceLogic {
  FirebaseServiceLogic(this.firestore);

  final FirebaseFirestore firestore;

  DocumentReference<Map<String, dynamic>> resolveDocumentReference({
    required String mainCollectionName,
    required String mainDocumentId,
    List<String>? subCollections,
    List<String>? subIds,
    bool allowAutoGeneratedSubIds = false,
  }) {
    DocumentReference<Map<String, dynamic>> docRef =
        firestore.collection(mainCollectionName).doc(mainDocumentId);

    final collections = subCollections ?? const <String>[];
    final ids = subIds ?? const <String>[];

    for (int i = 0; i < collections.length; i++) {
      final collectionRef = docRef.collection(collections[i]);
      final id = i < ids.length ? ids[i] : null;

      if (id != null && id.isNotEmpty) {
        docRef = collectionRef.doc(id);
        continue;
      }

      if (!allowAutoGeneratedSubIds) {
        throw ArgumentError(
          'Missing sub-document id for "${collections[i]}" at index $i.',
        );
      }

      docRef = collectionRef.doc();
    }

    return docRef;
  }

  CollectionReference<Map<String, dynamic>> resolveCollectionForGetAllData({
    required String mainCollectionName,
    required String mainDocumentId,
    List<String>? subCollections,
    List<String>? subIds,
  }) {
    DocumentReference<Map<String, dynamic>> docRef =
        firestore.collection(mainCollectionName).doc(mainDocumentId);

    final collections = subCollections ?? const <String>[];
    final ids = subIds ?? const <String>[];

    if (collections.isEmpty) {
      return docRef.collection(mainCollectionName);
    }

    for (int i = 0; i < collections.length; i++) {
      final collectionRef = docRef.collection(collections[i]);

      if (i == collections.length - 1) {
        return collectionRef;
      }

      final id = i < ids.length ? ids[i] : null;
      if (id == null || id.isEmpty) {
        throw ArgumentError(
          'Missing sub-document id for "${collections[i]}" at index $i.',
        );
      }
      docRef = collectionRef.doc(id);
    }

    throw StateError('Unable to resolve collection reference.');
  }

  CollectionReference<Map<String, dynamic>> resolveCollectionForQuery({
    required String collectionName,
    List<String>? subCollections,
    List<String>? subIds,
  }) {
    CollectionReference<Map<String, dynamic>> ref =
        firestore.collection(collectionName);

    final collections = subCollections ?? const <String>[];
    final ids = subIds ?? const <String>[];

    for (int i = 0; i < collections.length; i++) {
      final id = i < ids.length ? ids[i] : null;
      if (id != null && id.isNotEmpty) {
        ref = ref.doc(id).collection(collections[i]);
      } else {
        ref = ref.doc(collections[i]).collection(collections[i]);
      }
    }

    return ref;
  }
}
